name = "CoilFields"
uuid = "995d4d6b-9c7a-49f3-8fbe-7df0de3633c3"
authors = ["Spiffmeister <robospiff@gmail.com>"]
version = "0.1.0"

[deps]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OhMyThreads = "67456a42-1dca-4109-a031-0a68de7e3ad5"

[compat]
DelimitedFiles = "1.9.1"
LinearAlgebra = "1.11.0"
OhMyThreads = "0.8.3"
