
abstract type AbstractCoil end
abstract type AbstractCoilGeometry end
abstract type AbstractCoilSet end

const μ₀ = 4π * 1e-7

"""
    Coil{TT,GEOMETRY}

Geometry: Coil geometry
J: current
length: Coil resolution
"""
struct Coil{TT,GEOMETRY} <: AbstractCoil
    Geometry::GEOMETRY
    J::TT
    length::Int
end

Base.eachindex(coil::Coil) = 1:coil.length
Base.eltype(::Coil{TT}) where {TT} = TT
Base.getindex(coil::Coil{TT,GEO}, i) where {TT,GEO} = coil.Geometry[i]


"""
"""
struct PointCurvature{TT,VT} <: AbstractCoilGeometry
    points::VT
    normal::VT
    κ::Vector{TT}
end
# function PointCurvature(ℱ::Fourier{TT}, θ, ζ)
#     xyz = []
#     κ = []
#     new{TT,typeof(xyz)}(xyz, κ)
# end

struct ToroidalCoil{VT<:AbstractVector}
    point::VT
end




"""
    CoilGroup
Store coils as a vector of object [`Coil`](@ref)

A `CoilGroup` can be generated by using [`ReadCoilSet`](@ref)

TODO: Make GEOMETRY flexible
"""
struct CoilSet{TT,GEOMETRY} <: AbstractCoilSet
    Coils::Vector{Coil{TT,GEOMETRY}}
end
Base.iterate(CS::CoilSet, state=1) = state > length(CS.Coils) ? nothing : (CS.Coils[state], state + 1)
Base.eltype(::CoilSet{TT}) where {TT} = TT
Base.getindex(cs::CoilSet, i) = cs.Coils[i]



struct CompositeCoilSet{TT,TGROUP<:Tuple} <: AbstractCoilSet
    Group::TGROUP
    CompositeCoilSet(group) = new{eltype(group[1]),typeof(group)}(group)
end
Base.iterate(CS::CompositeCoilSet, state=1) = state > length(CS.Group) ? nothing : (CS.Group[state], state + 1)
Base.eltype(::CompositeCoilSet{TT}) where {TT} = TT
Base.getindex(cs::CompositeCoilSet, i) = cs.Group[i]
