
"""
    Coil{TT,GEOMETRY}

- `Geometry`: Coil geometry, see subtypes of `AbstractCoilGeometry`
- `J`: current
- `length`: Coil resolution

If the `Geometry` is an `AbstractArray`, the coil it can be indexed with `coil[i]`.

Also supports:
`eachindex` and `eltype`.
"""
struct Coil{TT,GEOMETRY} <: AbstractCoil
    Geometry::GEOMETRY
    J::TT
    length::Int
end
Base.eachindex(coil::Coil) = 1:coil.length
Base.eltype(::Coil{TT}) where {TT} = TT
Base.getindex(coil::Coil{TT,GEO}, i) where {TT,GEO} = coil.Geometry[i]


"""
    CoilSet{TT, GEOMETRY}

Store coils as a vector of object [`Coil`](@ref)

A `CoilSet` can be generated by using [`readcoilset`](@ref) or [`getcoilset`](@ref) from the [QUASR](https://quasr.flatironinstitute.org/) database.
"""
struct CoilSet{TT,GEOMETRY} <: AbstractCoilSet
    Coils::Vector{Coil{TT,GEOMETRY}}
end
Base.iterate(CS::CoilSet, state=1) = state > length(CS.Coils) ? nothing : (CS.Coils[state], state + 1)
Base.eltype(::CoilSet{TT}) where {TT} = TT
Base.getindex(cs::CoilSet, i) = cs.Coils[i]


"""
    CompositeCoilSet{TT,TGROUP<:Tuple}

Contains a `Group` of [`CoilSet`](@ref) objects.
"""
struct CompositeCoilSet{TT,TGROUP<:Tuple} <: AbstractCoilSet
    Group::TGROUP
    CompositeCoilSet(group) = new{eltype(group[1]),typeof(group)}(group)
end
Base.iterate(CS::CompositeCoilSet, state=1) = state > length(CS.Group) ? nothing : (CS.Group[state], state + 1)
Base.eltype(::CompositeCoilSet{TT}) where {TT} = TT
Base.getindex(cs::CompositeCoilSet, i) = cs.Group[i]
