name: Documentation

on:
  push:
    branches:
      - main # update to match your development branch (master, main, dev, trunk, ...)
    tags: '*'
  pull_request:

jobs:
  build:
    permissions:
      contents: write
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v2
        with:
          version: '1.11'
      - uses: julia-actions/cache@v2
      - name: Install dependencies
        # shell: julia --color=yes --project=docs {0}
        run: |
          julia --project=docs/ -e '
          using Pkg
          Pkg.add("Documenter")
          Pkg.add("Literate")
          Pkg.add("GLMakie")
          Pkg.develop(PackageSpec(path=pwd()))
          Pkg.instantiate()'
      - name: Build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
        run: >
          DISPLAY=:0 xvfb-run -s '-screen 0 1024x768x24' 
          julia --project=docs/ docs/make.jl
